name: Pages

on:
  pull_request:
  push:
    branches: 'main'

permissions:
    contents: write
    pull-requests: write

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set env
        run: |
          GIT_BRANCH="TEST"
          if [[ $GIT_BRANCH == "ST" ]]; then
            DEST_DIR="/"
            {
            echo 'CLEAN_EXCLUDE<<EOF'
            echo "/branch/*"
            echo "/allure-action/*"
            echo EOF
            } >> "$GITHUB_ENV"
          else
            DEST_DIR="/branch/${GIT_BRANCH//[^a-zA-Z0-9_]/_}"
            echo "CLEAN_EXCLUDE="/nothing"" >> $GITHUB_ENV
          fi
          echo "GIT_BRANCH=$GIT_BRANCH" >> $GITHUB_ENV
          echo "DEST_DIR=$DEST_DIR" >> $GITHUB_ENV
      - name: Publish docs
        uses: JamesIves/github-pages-deploy-action@v4.4.3
        with:
          clean: true
          clean-exclude: |
            ${{ env.CLEAN_EXCLUDE }}
          single-commit: true
          folder: .
